### ISSUE TITLE
[Linux] Reload doesn't work

### ISSUE THREAD

**Issue by graue** [jeena/Bungloo#107]
Right clicking in any window and choosing Reload seems to never reload the contents. It just goes blank and stays that way until Tentia is restarted.

**Comment by jeena** [comment]
I think I should just remove the reload thingy, it is one of the defaults for a webview which don't make sense in a app context.

**Comment by graue** [comment]
It makes sense in conversation view or someone's profile, doesn't it? Or do you constantly check for new posts there too?

**Comment by jeena** [comment]
Hm I could check for new posts on the profile view, you're right, didn't think about it because I just open this view for a short time and close it when I'm done.

Conversation view is quite a complicated thing, there perhaps a reload would make sense where it would just start the recursive loading of all items again or something like that. I will have to think about it.

**Comment by jeena** [comment]
I removed the reload menu.
