### ISSUE TITLE
Remember open windows and location on quit

### ISSUE THREAD

**Issue by tjreo** [jeena/Bungloo#126]
When quitting the app, save the state. Remember which windows are open and where they are located. 

You are MAKING ME CRAZY, Tentia! 

[Don't make me angry. You won't like me when I'm angry.](http://www.imdb.com/title/tt0077031/quotes)

**Comment by jeena** [comment]
It already remembers where the windows are located, but it always only opens with the Timeline window open, because the other windows mostly don't have any state yet (like the conversation window or the profile window) and it doesn't make sense to open empty windows. Saving the state of that windows seems just too much work for no reason because mostly you click on something if you want to see the Profile/Conversation/Reply/New Post, etc.

I don't think it will be implemented any time soon therefor I am closing this issue for now. But you are welcome to send in a pull request if you decide to implement it on your own :)

**Comment by poweruser82** [comment]
It can make sense for the mention window

**Comment by jeena** [comment]
Yes, true but I don't see a possibility to do that in the Interface Builder, so I'd have to do it manually, perhaps in the future.
