### ISSUE TITLE
Mention suggestions

### ISSUE THREAD

**Issue by Nygu** [jeena/Bungloo#138]
When a user types ^, @ or +, a selection panel should show up that allows searching for the right person to mention. This way you no longer have to know the exact entity of your followings in order to be able to mention them.

**Comment by jeena** [comment]
Yes I fully agree, sadly the code for that will be quite complex because we'll need to work with augmented string and menues and stuff in Objective-C and Python because there is no way to open menues which are bigger then the new message window. I would really like to learn how to do that but it is not an easy task.

**Comment by jeena** [comment]
Ok this is fixed in 2.0
