### ISSUE TITLE
Attaching more than one image to a post

### ISSUE THREAD

**Issue by ckruse** [jeena/Bungloo#211]
It would be nice if one could attach more than just one image to a post

**Comment by bnb** [comment]
Not sure, but I _think_ this isn't possible with 0.2, though it might be with 0.3.

**Comment by jeena** [comment]
It has always been possible, I just chose to implement with one because 
that way the UI was much easier to implement and for 3 months nobody 
even came up with the idea of posting more then one picture at the same 
time.

Anyway, if I am going to implement that some day then probably with a 
album functionality or something.

**Comment by jeena** [comment]
Image upload was removed in 2.0
