### ISSUE TITLE
URL at beginning of post not linked

### ISSUE THREAD

**Issue by tjreo** [jeena/Bungloo#51]
It appears that if the post begins with a URL that the URL does not become a link. [Here is a screen shot](https://dl.dropbox.com/u/2740824/Screen%20Shot%202012-11-12%20at%208.29.08%20PM.png) of a post from ^daniel.

**Comment by jeena** [comment]
Hm, true, and there is one more problem, if a URL is enclosed in some kind of parenthesis then the parenthesis get in the way too so it is not clickable. It is because of the regex I use in https://github.com/jeena/Tentia/blob/master/WebKit/scripts/helper/Core.js#L381 which I just found a couple of years ago on the internet. If someone could make it better I would be supper happy.

I think this is where a community driven development could show its strength, at least in the beginning you guys could help me fixing small stuff like that so I can focus on the bigger picture like a Linux version or Reposts, etc.

The easiest way would be to clone, fix it and send me a pull request, then I would just have to accept it :-)

**Comment by riccard0** [comment]
You can use this pretty comprehensive regex: http://daringfireball.net/2010/07/improved_regex_for_matching_urls
It’s the one https://marco.tent.is is using for Tentr.

**Comment by jeena** [comment]
Nice, thanks, I will build in this one into the next version :)
