### ISSUE TITLE
Loading indicator on windows opening

### ISSUE THREAD

**Issue by poweruser82** [jeena/Bungloo#81]
At application launch (when timeline window opens) and on opening conversation and profile views the window is blank (but nicer after #47). Tentia needs something to indicate it is loading the content.
A spinner ![Spinner](http://krypted.com/wp-content/uploads/2010/08/spinner.gif) would fit.

**Comment by jeena** [comment]
The thing is that it is only because it is loading 400+ status updates, I change it during development sometimes to 40 and it is superfast. I was thinking about load on scroll which would load while you scroll down, then we would only need to load perhaps 20 on start or something and the startup time would be very short.

But yeah, still such a loading indicator, but a nicer one would be a good thing, I will try to implement it.

**Comment by riccard0** [comment]
I agree both with the need of a loading indicator and with incremental loading of posts.

**Comment by poweruser82** [comment]
A situation in which a loading indicator is particularly useful is the conversation view. You never know if it is loading replies or it's done.

**Comment by jeena** [comment]
fixed with https://github.com/jeena/Bungloo/commit/b210e6ee323daa24246445c41afbaa5202cd34ee
