### ISSUE TITLE
[Linux] Some self-hosted Tentities aren't being highlighted.

### ISSUE THREAD

**Issue by bnb** [jeena/Bungloo#99]
I've noticed that some self-hosted Tentities aren't being highlighted/abbreviated with their "real name". The example that I have right here is that of ^https://scott.mn. Jacob Cook make a post mentioning Jeena and Scott, and Scott's name wasn't highlighted, but rather it was simply plain text. Not sure what is causing this, but it is an issue.

**Comment by jeena** [comment]
Hm yeah that happens sometimes I don't know either why, but sometimes the servers don't respond or something. The way I fixed it in OS X was that I implemented a cache, that cache doesn't work yet on Linux because it doesn't use localStorage yet, I will try to fix it, I think it is only a matter of just setting it up right.

**Comment by jeena** [comment]
It seems that this was some problem of tentd which seems to have been resolved so nowadays this doesn't happen anymore.
